name: isomanagement-frontend
region: nyc
services:
  # Frontend Application Service
  - name: frontend
    github:
      repo: dancan-sandys/isomanagement
      branch: master
      source_dir: /frontend
    build_command: npm install --legacy-peer-deps && npm run build
    run_command: npx serve -s build -l $PORT --single
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      failure_threshold: 3
      success_threshold: 1
    envs:
      - key: REACT_APP_API_URL
        value: https://isomanagement-backend.ondigitalocean.app/api/v1
      - key: REACT_APP_ENV
        value: production
      - key: REACT_APP_DEBUG
        value: "false"
      - key: GENERATE_SOURCEMAP
        value: "false"
      - key: NODE_ENV
        value: production
