from fastapi import APIRouter
from app.api.v1.endpoints import auth, dashboard, documents, haccp, prp, notifications, settings, suppliers, traceability, rbac, users, profile, nonconformance, audits, training, risk, equipment, allergen_label, management_review, complaints, search, demo, objectives, production

api_router = APIRouter()

# Include endpoint routers
api_router.include_router(auth.router, prefix="/auth", tags=["authentication"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["dashboard"])
api_router.include_router(documents.router, prefix="/documents", tags=["documents"])
api_router.include_router(haccp.router, prefix="/haccp", tags=["haccp"])
api_router.include_router(prp.router, prefix="/prp", tags=["prp"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(settings.router, prefix="/settings", tags=["settings"])
api_router.include_router(suppliers.router, prefix="/suppliers", tags=["suppliers"])
api_router.include_router(traceability.router, prefix="/traceability", tags=["traceability"])
api_router.include_router(rbac.router, prefix="/rbac", tags=["rbac"])
api_router.include_router(users.router, prefix="/users", tags=["users"]) 
api_router.include_router(profile.router, prefix="/profile", tags=["profile"])
api_router.include_router(nonconformance.router, prefix="/nonconformance", tags=["nonconformance"])
api_router.include_router(audits.router, prefix="/audits", tags=["audits"])
api_router.include_router(training.router, prefix="/training", tags=["training"])
api_router.include_router(risk.router, prefix="/risk", tags=["risk"])
api_router.include_router(equipment.router, prefix="/equipment", tags=["equipment"])
api_router.include_router(allergen_label.router, prefix="/allergen-label", tags=["allergen_label"]) 
api_router.include_router(management_review.router, prefix="/management-reviews", tags=["management_reviews"])
api_router.include_router(complaints.router, prefix="/complaints", tags=["complaints"]) 
api_router.include_router(search.router, prefix="/search", tags=["search"]) 
api_router.include_router(demo.router, prefix="/demo", tags=["demo"])
api_router.include_router(objectives.router, prefix="/objectives", tags=["objectives"])
api_router.include_router(production.router, prefix="/production", tags=["production"])