import { ProductTemplate, HACCPProcessStep, HACCPFlowConnection, HACCPNodeType } from './types';

// Predefined HACCP flowchart templates for common dairy products
export const productTemplates: ProductTemplate[] = [
  {
    id: 'milk_pasteurized',
    name: 'Pasteurized Milk',
    description: 'Standard HTST pasteurization process for fluid milk',
    category: 'milk',
    defaultNodes: [
      {
        id: 'start_1',
        type: HACCPNodeType.START,
        label: 'Start',
        position: { x: 250, y: 50 },
        data: {
          stepNumber: 1,
          description: 'Beginning of milk processing',
          isRequired: true,
        },
      },
      {
        id: 'receive_1',
        type: HACCPNodeType.RAW_MATERIAL_RECEIVING,
        label: 'Raw Milk Receiving',
        position: { x: 250, y: 150 },
        data: {
          stepNumber: 2,
          description: 'Receive raw milk from dairy farms',
          temperature: { max: 6, unit: 'C' as const },
          equipment: 'Milk tanker, receiving dock',
          hazards: [
            {
              id: 'recv_bio_1',
              type: 'biological' as const,
              description: 'Pathogenic bacteria (E. coli, Salmonella, Listeria)',
              likelihood: 3,
              severity: 4,
              riskLevel: 'high' as const,
              controlMeasures: 'Supplier verification, temperature monitoring, quality testing',
            },
            {
              id: 'recv_chem_1',
              type: 'chemical' as const,
              description: 'Antibiotic residues',
              likelihood: 2,
              severity: 3,
              riskLevel: 'medium' as const,
              controlMeasures: 'Supplier certification, residue testing',
            },
          ],
        },
      },
      {
        id: 'inspect_1',
        type: HACCPNodeType.INSPECTION,
        label: 'Quality Inspection',
        position: { x: 250, y: 250 },
        data: {
          stepNumber: 3,
          description: 'Visual inspection and quality tests',
          hazards: [
            {
              id: 'insp_phy_1',
              type: 'physical' as const,
              description: 'Foreign objects',
              likelihood: 1,
              severity: 3,
              riskLevel: 'low' as const,
              controlMeasures: 'Visual inspection, filtration',
            },
          ],
        },
      },
      {
        id: 'storage_1',
        type: HACCPNodeType.COLD_STORAGE,
        label: 'Cold Storage',
        position: { x: 250, y: 350 },
        data: {
          stepNumber: 4,
          description: 'Temporary storage before processing',
          temperature: { min: 2, max: 6, target: 4, unit: 'C' as const },
          equipment: 'Refrigerated silos',
          hazards: [
            {
              id: 'stor_bio_1',
              type: 'biological' as const,
              description: 'Bacterial growth due to temperature abuse',
              likelihood: 2,
              severity: 4,
              riskLevel: 'high' as const,
              controlMeasures: 'Continuous temperature monitoring, alarm system',
              isCCP: true,
            },
          ],
          ccp: {
            number: 'CCP-1',
            criticalLimits: [
              { parameter: 'Temperature', max: 6, unit: '°C' },
            ],
            monitoringFrequency: 'Continuous',
            monitoringMethod: 'Temperature data logger with alarms',
            responsiblePerson: 'Production Supervisor',
            correctiveActions: 'Adjust cooling system, check product temperature, isolate affected product',
            verificationMethod: 'Daily review of temperature records, calibration of instruments',
          },
        },
      },
      {
        id: 'standard_1',
        type: HACCPNodeType.STANDARDIZATION,
        label: 'Fat Standardization',
        position: { x: 250, y: 450 },
        data: {
          stepNumber: 5,
          description: 'Adjust fat content to desired level',
          equipment: 'Cream separator, standardization unit',
        },
      },
      {
        id: 'pasteur_1',
        type: HACCPNodeType.PASTEURIZATION,
        label: 'HTST Pasteurization',
        position: { x: 250, y: 550 },
        data: {
          stepNumber: 6,
          description: 'High Temperature Short Time pasteurization',
          temperature: { min: 72, target: 72, unit: 'C' as const },
          time: { duration: 15, unit: 'seconds' as const },
          equipment: 'Plate heat exchanger',
          hazards: [
            {
              id: 'past_bio_1',
              type: 'biological' as const,
              description: 'Survival of pathogenic bacteria and vegetative pathogens',
              likelihood: 2,
              severity: 5,
              riskLevel: 'critical' as const,
              controlMeasures: 'Time and temperature monitoring, flow rate control',
              isCCP: true,
            },
          ],
          ccp: {
            number: 'CCP-2',
            criticalLimits: [
              { parameter: 'Temperature', min: 72, unit: '°C' },
              { parameter: 'Time', min: 15, unit: 'seconds' },
            ],
            monitoringFrequency: 'Continuous',
            monitoringMethod: 'Temperature recorder and flow rate monitoring',
            responsiblePerson: 'Process Operator',
            correctiveActions: 'Reprocess product, adjust time/temperature, stop production until correction',
            verificationMethod: 'Daily calibration check, weekly product testing',
          },
        },
      },
      {
        id: 'cool_1',
        type: HACCPNodeType.COOLING,
        label: 'Cooling',
        position: { x: 250, y: 650 },
        data: {
          stepNumber: 7,
          description: 'Rapid cooling to storage temperature',
          temperature: { target: 4, unit: 'C' as const },
          equipment: 'Cooling section of plate heat exchanger',
          hazards: [
            {
              id: 'cool_bio_1',
              type: 'biological' as const,
              description: 'Recontamination or slow cooling allowing bacterial growth',
              likelihood: 2,
              severity: 4,
              riskLevel: 'high' as const,
              controlMeasures: 'Rapid cooling, sanitary design, positive pressure',
            },
          ],
        },
      },
      {
        id: 'homog_1',
        type: HACCPNodeType.HOMOGENIZATION,
        label: 'Homogenization',
        position: { x: 250, y: 750 },
        data: {
          stepNumber: 8,
          description: 'Homogenize for uniform fat distribution',
          equipment: 'High-pressure homogenizer',
        },
      },
      {
        id: 'fill_1',
        type: HACCPNodeType.FILLING,
        label: 'Aseptic Filling',
        position: { x: 250, y: 850 },
        data: {
          stepNumber: 9,
          description: 'Fill into sterile containers',
          equipment: 'Aseptic filling machine',
          hazards: [
            {
              id: 'fill_bio_1',
              type: 'biological' as const,
              description: 'Post-pasteurization contamination',
              likelihood: 2,
              severity: 4,
              riskLevel: 'high' as const,
              controlMeasures: 'Aseptic conditions, sanitary design, positive pressure',
              isCCP: true,
            },
          ],
          ccp: {
            number: 'CCP-3',
            criticalLimits: [
              { parameter: 'Container sterility', min: 1, unit: 'log reduction' },
              { parameter: 'Environmental pressure', min: 5, unit: 'Pa positive' },
            ],
            monitoringFrequency: 'Each batch',
            monitoringMethod: 'Sterility testing, pressure monitoring',
            responsiblePerson: 'QA Technician',
            correctiveActions: 'Re-sterilize containers, check sealing integrity, isolate suspect product',
            verificationMethod: 'Weekly environmental monitoring, monthly sterility validation',
          },
        },
      },
      {
        id: 'seal_1',
        type: HACCPNodeType.SEALING,
        label: 'Container Sealing',
        position: { x: 250, y: 950 },
        data: {
          stepNumber: 10,
          description: 'Hermetically seal containers',
          equipment: 'Heat sealing unit',
        },
      },
      {
        id: 'label_1',
        type: HACCPNodeType.LABELING,
        label: 'Labeling',
        position: { x: 250, y: 1050 },
        data: {
          stepNumber: 11,
          description: 'Apply product labels',
          equipment: 'Labeling machine',
          hazards: [
            {
              id: 'label_allergen_1',
              type: 'allergen' as const,
              description: 'Incorrect allergen information',
              likelihood: 1,
              severity: 5,
              riskLevel: 'critical' as const,
              controlMeasures: 'Label verification, batch tracking',
            },
          ],
        },
      },
      {
        id: 'storage_final',
        type: HACCPNodeType.COLD_STORAGE,
        label: 'Final Cold Storage',
        position: { x: 250, y: 1150 },
        data: {
          stepNumber: 12,
          description: 'Store finished product',
          temperature: { max: 6, unit: 'C' as const },
          equipment: 'Cold storage warehouse',
        },
      },
      {
        id: 'ship_1',
        type: HACCPNodeType.SHIPPING,
        label: 'Shipping',
        position: { x: 250, y: 1250 },
        data: {
          stepNumber: 13,
          description: 'Ship to customers',
          temperature: { max: 6, unit: 'C' as const },
          equipment: 'Refrigerated trucks',
        },
      },
      {
        id: 'end_1',
        type: HACCPNodeType.END,
        label: 'End',
        position: { x: 250, y: 1350 },
        data: {
          stepNumber: 14,
          description: 'End of process',
          isRequired: true,
        },
      },
    ],
    defaultEdges: [
      { id: 'e1-2', source: 'start_1', target: 'receive_1' },
      { id: 'e2-3', source: 'receive_1', target: 'inspect_1' },
      { id: 'e3-4', source: 'inspect_1', target: 'storage_1' },
      { id: 'e4-5', source: 'storage_1', target: 'standard_1' },
      { id: 'e5-6', source: 'standard_1', target: 'pasteur_1' },
      { id: 'e6-7', source: 'pasteur_1', target: 'cool_1' },
      { id: 'e7-8', source: 'cool_1', target: 'homog_1' },
      { id: 'e8-9', source: 'homog_1', target: 'fill_1' },
      { id: 'e9-10', source: 'fill_1', target: 'seal_1' },
      { id: 'e10-11', source: 'seal_1', target: 'label_1' },
      { id: 'e11-12', source: 'label_1', target: 'storage_final' },
      { id: 'e12-13', source: 'storage_final', target: 'ship_1' },
      { id: 'e13-14', source: 'ship_1', target: 'end_1' },
    ],
  },
  
  {
    id: 'yogurt_production',
    name: 'Yogurt Production',
    description: 'Fermented yogurt production process',
    category: 'yogurt',
    defaultNodes: [
      {
        id: 'start_y1',
        type: HACCPNodeType.START,
        label: 'Start',
        position: { x: 250, y: 50 },
        data: {
          stepNumber: 1,
          description: 'Beginning of yogurt production',
          isRequired: true,
        },
      },
      {
        id: 'receive_y1',
        type: HACCPNodeType.RAW_MATERIAL_RECEIVING,
        label: 'Milk Receiving',
        position: { x: 250, y: 150 },
        data: {
          stepNumber: 2,
          description: 'Receive raw milk for yogurt production',
          temperature: { max: 6, unit: 'C' as const },
          hazards: [
            {
              id: 'recv_bio_y1',
              type: 'biological' as const,
              description: 'Pathogenic bacteria in raw milk',
              likelihood: 3,
              severity: 4,
              riskLevel: 'high' as const,
              controlMeasures: 'Supplier verification, temperature monitoring',
            },
          ],
        },
      },
      {
        id: 'standard_y1',
        type: HACCPNodeType.STANDARDIZATION,
        label: 'Milk Standardization',
        position: { x: 250, y: 250 },
        data: {
          stepNumber: 3,
          description: 'Adjust fat and protein content',
          equipment: 'Standardization tank',
        },
      },
      {
        id: 'pasteur_y1',
        type: HACCPNodeType.PASTEURIZATION,
        label: 'Pasteurization',
        position: { x: 250, y: 350 },
        data: {
          stepNumber: 4,
          description: 'Heat treatment for yogurt base',
          temperature: { min: 85, target: 85, unit: 'C' as const },
          time: { duration: 30, unit: 'minutes' as const },
          equipment: 'Batch pasteurizer',
          hazards: [
            {
              id: 'past_bio_y1',
              type: 'biological' as const,
              description: 'Inadequate heat treatment',
              likelihood: 2,
              severity: 5,
              riskLevel: 'critical' as const,
              controlMeasures: 'Time and temperature monitoring',
              isCCP: true,
            },
          ],
          ccp: {
            number: 'CCP-1',
            criticalLimits: [
              { parameter: 'Temperature', min: 85, unit: '°C' },
              { parameter: 'Time', min: 30, unit: 'minutes' },
            ],
            monitoringFrequency: 'Each batch',
            monitoringMethod: 'Temperature chart recorder',
            responsiblePerson: 'Process Operator',
            correctiveActions: 'Reprocess, adjust parameters',
            verificationMethod: 'Weekly thermometer calibration',
          },
        },
      },
      {
        id: 'cool_y1',
        type: HACCPNodeType.COOLING,
        label: 'Cooling to Incubation Temperature',
        position: { x: 250, y: 450 },
        data: {
          stepNumber: 5,
          description: 'Cool to fermentation temperature',
          temperature: { target: 42, unit: 'C' as const },
          equipment: 'Cooling coils',
        },
      },
      {
        id: 'culture_y1',
        type: HACCPNodeType.MIXING,
        label: 'Culture Addition',
        position: { x: 250, y: 550 },
        data: {
          stepNumber: 6,
          description: 'Add starter cultures',
          equipment: 'Culture dosing system',
          hazards: [
            {
              id: 'cult_bio_y1',
              type: 'biological' as const,
              description: 'Contaminated or inactive cultures',
              likelihood: 2,
              severity: 4,
              riskLevel: 'high' as const,
              controlMeasures: 'Culture testing, supplier verification',
            },
          ],
        },
      },
      {
        id: 'ferment_y1',
        type: HACCPNodeType.FERMENTATION,
        label: 'Fermentation',
        position: { x: 250, y: 650 },
        data: {
          stepNumber: 7,
          description: 'Controlled lactic acid fermentation',
          temperature: { target: 42, unit: 'C' as const },
          ph: { target: 4.6 },
          time: { duration: 4, unit: 'hours' as const },
          equipment: 'Fermentation tank',
          hazards: [
            {
              id: 'ferm_bio_y1',
              type: 'biological' as const,
              description: 'Uncontrolled fermentation or contamination',
              likelihood: 2,
              severity: 4,
              riskLevel: 'high' as const,
              controlMeasures: 'pH and temperature monitoring',
              isCCP: true,
            },
          ],
          ccp: {
            number: 'CCP-2',
            criticalLimits: [
              { parameter: 'pH', max: 4.6, unit: 'pH units' },
              { parameter: 'Temperature', min: 40, max: 45, unit: '°C' },
            ],
            monitoringFrequency: 'Every hour',
            monitoringMethod: 'pH meter and thermometer',
            responsiblePerson: 'Fermentation Operator',
            correctiveActions: 'Adjust temperature, extend fermentation time, discard batch if pH not achieved',
            verificationMethod: 'Daily calibration of pH meter',
          },
        },
      },
      {
        id: 'cool_final_y1',
        type: HACCPNodeType.COOLING,
        label: 'Final Cooling',
        position: { x: 250, y: 750 },
        data: {
          stepNumber: 8,
          description: 'Cool to packaging temperature',
          temperature: { target: 4, unit: 'C' as const },
          equipment: 'Cooling system',
        },
      },
      {
        id: 'fill_y1',
        type: HACCPNodeType.FILLING,
        label: 'Filling',
        position: { x: 250, y: 850 },
        data: {
          stepNumber: 9,
          description: 'Fill into containers',
          temperature: { max: 10, unit: 'C' as const },
          equipment: 'Filling machine',
          hazards: [
            {
              id: 'fill_bio_y1',
              type: 'biological' as const,
              description: 'Post-fermentation contamination',
              likelihood: 2,
              severity: 4,
              riskLevel: 'high' as const,
              controlMeasures: 'Sanitary filling conditions',
            },
          ],
        },
      },
      {
        id: 'seal_y1',
        type: HACCPNodeType.SEALING,
        label: 'Sealing',
        position: { x: 250, y: 950 },
        data: {
          stepNumber: 10,
          description: 'Seal containers',
          equipment: 'Sealing machine',
        },
      },
      {
        id: 'storage_y1',
        type: HACCPNodeType.COLD_STORAGE,
        label: 'Cold Storage',
        position: { x: 250, y: 1050 },
        data: {
          stepNumber: 11,
          description: 'Store finished yogurt',
          temperature: { max: 6, unit: 'C' as const },
        },
      },
      {
        id: 'ship_y1',
        type: HACCPNodeType.SHIPPING,
        label: 'Shipping',
        position: { x: 250, y: 1150 },
        data: {
          stepNumber: 12,
          description: 'Ship to customers',
          temperature: { max: 6, unit: 'C' as const },
        },
      },
      {
        id: 'end_y1',
        type: HACCPNodeType.END,
        label: 'End',
        position: { x: 250, y: 1250 },
        data: {
          stepNumber: 13,
          description: 'End of yogurt production',
          isRequired: true,
        },
      },
    ],
    defaultEdges: [
      { id: 'ey1-2', source: 'start_y1', target: 'receive_y1' },
      { id: 'ey2-3', source: 'receive_y1', target: 'standard_y1' },
      { id: 'ey3-4', source: 'standard_y1', target: 'pasteur_y1' },
      { id: 'ey4-5', source: 'pasteur_y1', target: 'cool_y1' },
      { id: 'ey5-6', source: 'cool_y1', target: 'culture_y1' },
      { id: 'ey6-7', source: 'culture_y1', target: 'ferment_y1' },
      { id: 'ey7-8', source: 'ferment_y1', target: 'cool_final_y1' },
      { id: 'ey8-9', source: 'cool_final_y1', target: 'fill_y1' },
      { id: 'ey9-10', source: 'fill_y1', target: 'seal_y1' },
      { id: 'ey10-11', source: 'seal_y1', target: 'storage_y1' },
      { id: 'ey11-12', source: 'storage_y1', target: 'ship_y1' },
      { id: 'ey12-13', source: 'ship_y1', target: 'end_y1' },
    ],
  },

  // Add basic template for custom process
  {
    id: 'basic_template',
    name: 'Basic Process Template',
    description: 'Basic template with start and end nodes',
    category: 'custom',
    defaultNodes: [
      {
        id: 'start_basic',
        type: HACCPNodeType.START,
        label: 'Start',
        position: { x: 250, y: 100 },
        data: {
          stepNumber: 1,
          description: 'Start of process',
          isRequired: true,
        },
      },
      {
        id: 'end_basic',
        type: HACCPNodeType.END,
        label: 'End',
        position: { x: 250, y: 300 },
        data: {
          stepNumber: 2,
          description: 'End of process',
          isRequired: true,
        },
      },
    ],
    defaultEdges: [
      { id: 'ebasic1-2', source: 'start_basic', target: 'end_basic' },
    ],
  },
];

export const getTemplateByCategory = (category: string): ProductTemplate[] => {
  return productTemplates.filter(template => template.category === category);
};

export const getTemplateById = (id: string): ProductTemplate | undefined => {
  return productTemplates.find(template => template.id === id);
};
