name: isomanagement-backend
region: nyc
services:
  # Backend API Service
  - name: backend
    source_dir: /
    github:
      repo: dancan-sandys/isomanagement/backend
      branch: master
    build_command: pip install -r requirements-production.txt
    run_command: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      failure_threshold: 3
      success_threshold: 1
    envs:
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        type: SECRET
      - key: DATABASE_TYPE
        value: postgresql
      - key: SECRET_KEY
        value: ${SECRET_KEY}
        type: SECRET
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: APP_NAME
        value: "ISO 22000 FSMS"
      - key: APP_VERSION
        value: "1.0.0"
      - key: DEBUG
        value: "False"
      - key: ENVIRONMENT
        value: "production"
      - key: ALLOWED_ORIGINS
        value: '["https://iso22000-fsms-frontend.ondigitalocean.app","*"]'
      - key: ALLOWED_CREDENTIALS
        value: "True"
      - key: MAX_FILE_SIZE
        value: "10485760"
      - key: ALLOWED_FILE_TYPES
        value: "pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png,gif"
      - key: ENABLE_EMAIL_NOTIFICATIONS
        value: "True"
      - key: SMTP_HOST
        value: ${SMTP_HOST}
        type: SECRET
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: ${isocreatesoftwares@gmail.com}
        type: SECRET
      - key: SMTP_PASSWORD
        value: ${olmq engf ouun ionj}
        type: SECRET
      - key: SMTP_TLS
        value: "True"
      - key: LOG_LEVEL
        value: "INFO"
      - key: LOG_FORMAT
        value: "json"
      - key: BACKUP_ENABLED
        value: "True"
      - key: BACKUP_RETENTION_DAYS
        value: "30"
      - key: RATE_LIMIT_PER_MINUTE
        value: "100"
      - key: AWS_ACCESS_KEY_ID
        value: ${SPACES_ACCESS_KEY}
        type: SECRET
      - key: AWS_SECRET_ACCESS_KEY
        value: ${SPACES_SECRET_KEY}
        type: SECRET
      - key: AWS_BUCKET_NAME
        value: ${SPACES_BUCKET_NAME}
      - key: AWS_REGION
        value: ${SPACES_REGION}
      - key: AWS_ENDPOINT_URL
        value: ${SPACES_ENDPOINT_URL}

databases:
  # PostgreSQL Database
  - name: db
    engine: PG
    version: "15"
    production: true
    cluster_name: iso22000-fsms-db
    db_name: iso22000_fsms
    db_user: iso22000_user

# Environment Variables (global)
envs:
  - key: SECRET_KEY
    value: your-super-secret-key-change-this-in-production
    type: SECRET
  - key: SMTP_HOST
    value: smtp.gmail.com
    type: SECRET
  - key: SMTP_USER
    value: your-email@gmail.com
    type: SECRET
  - key: SMTP_PASSWORD
    value: your-app-password
    type: SECRET
  - key: SPACES_ACCESS_KEY
    value: your-spaces-access-key
    type: SECRET
  - key: SPACES_SECRET_KEY
    value: your-spaces-secret-key
    type: SECRET
  - key: SPACES_BUCKET_NAME
    value: iso22000-fsms-files
  - key: SPACES_REGION
    value: nyc3
  - key: SPACES_ENDPOINT_URL
    value: https://nyc3.digitaloceanspaces.com